name: Build FreeBSD Container Image

on:
  repository_dispatch:
    types:
      - build

  workflow_dispatch:
    inputs:
      CPU:
        description: "Which machine type (amd64 or arm64) do you want to build? (Default: amd64)"
        type: choice
        options:
          - amd64
          - arm64
        default: amd64
        required: true
      LATEST:
        description: "Whether the 'latest' tag should be created (Default: false)"
        type: boolean
        default: false
        required: true

jobs:
  build:
    name: FreeBSD-${{ matrix.freebsd_version }}-${{ github.event.inputs.CPU || github.event.client_payload.cpu }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        freebsd_version:
          - "15.0"
          - "14.1"

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y buildah libarchive-tools podman
          sudo update-alternatives --install /usr/local/bin/tar tar /usr/bin/bsdtar 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Store parameters in environmental variables
        run: |
          echo "FREEBSD_VERSION=${{ matrix.freebsd_version }}" >> $GITHUB_ENV
          echo "CPU=${{ github.event.inputs.CPU || github.event.client_payload.cpu }}" >> $GITHUB_ENV
          echo "LATEST=${{ github.event.inputs.LATEST || github.event.client_payload.latest }}" >> $GITHUB_ENV

      - name: Show parameters
        run: |
          echo $FREEBSD_VERSION
          echo $CPU
          echo $LATEST

      # XXX Use BSD tar
      - name: Build image
        run: |
          sudo sh ./build.sh --cpu=${{ env.CPU }} --freebsd_version=${{ env.FREEBSD_VERSION }} --latest_tag=${{ env.LATEST }}

      - name: Check image
        run: |
          podman images

      #     # XXX Settle on versioning
      #     if [[ "${{ env.FREEBSD_VERSION }}" != "15.0" ]]; then
      #       FREEBSD_VERSION_WITH_SUFFIX=${{ env.FREEBSD_VERSION }}-RELEASE
      #     else
      #       FREEBSD_VERSION_WITH_SUFFIX=${{ env.FREEBSD_VERSION }}-CURRENT
      #     fi
      #     if [[ "${{ env.CPU }}" != "amd64" ]]; then
      #       CPU_SUFFIX=-${{ env.CPU }}
      #     fi
      #     podman run ghcr.io/${{ github.repository_owner }}/freebsd:${FREEBSD_VERSION_WITH_SUFFIX}${CPU_SUFFIX} uname -a

      # - name: Login to ghcr.io
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GITHUB_PAT }}
      #     password: ${{ secrets.GITHUB_PAT }}

      # - name: Push images to ghcr.io
      #   run: podman push ghcr.io/${{ github.repository_owner }}/freebsd --all-tags
