name: Build FreeBSD Container Image

on:
  repository_dispatch:
    types:
      - build

  workflow_dispatch:
    inputs:
      FREEBSD_VERSION:
        description: "The version of FreeBSD to be built (Default: 15.0)"
        type: choice
        options:
          - "15.0"
          - "14.1"
        default: "15.0"
        required: true
      LATEST:
        description: "Whether the 'latest' tag should be created"
        type: boolean
        default: true
        required: false

jobs:
  build:
    name: FreeBSD-${{ github.event.inputs.FREEBSD_VERSION || github.event.client_payload.freebsd_version }}-${{ matrix.cpu }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cpu:
        - amd64
        - arm64
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libarchive-tools
          sudo update-alternatives --install /usr/local/bin/tar tar /usr/bin/bsdtar 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Store parameters in environmental variables
        run: |
          echo "FREEBSD_VERSION=${{ github.event.inputs.FREEBSD_VERSION || github.event.client_payload.freebsd_version }}" >> $GITHUB_ENV
          echo "CPU=${{ matrix.cpu }}" >> $GITHUB_ENV
          echo "LATEST=${{ github.event.inputs.LATEST || github.event.client_payload.latest }}" >> $GITHUB_ENV
          echo "REGISTRY_PATH=ghcr.io/${{ github.repository_owner }}/" >> $GITHUB_ENV

      - name: Build image
        run: |
          sudo sh ./build.sh -c ${{ env.CPU }} -f ${{ env.FREEBSD_VERSION }}${{ env.LATEST == true && ' -l' || '' }} -r ${{ env.REGISTRY_PATH }}

      - name: Check image
        run: |
          sudo podman images
          # XXX Uncomment on runners with a FreeBSD kernel
          # sudo podman run ${{ env.REGISTRY_PATH }}freebsd-${{ env.CPU }}:${{ env.FREEBSD_VERSION }} uname -a

  build_manifest:
    name: FreeBSD-${{ github.event.inputs.FREEBSD_VERSION || github.event.client_payload.freebsd_version }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_SECRET }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Store parameters in environmental variables
        run: |
          echo "FREEBSD_VERSION=${{ github.event.inputs.FREEBSD_VERSION || github.event.client_payload.freebsd_version }}" >> $GITHUB_ENV
          # XXX missing ${{ env.LATEST == true && 'latest' || '' }}
          # echo "LATEST=${{ github.event.inputs.LATEST || github.event.client_payload.latest }}" >> $GITHUB_ENV
          echo "REGISTRY_PATH=ghcr.io/${{ github.repository_owner }}/" >> $GITHUB_ENV

      - name: Build manifest
        run: |
          sudo buildah manifest create ${{ env.REGISTRY_PATH }}freebsd:${{ env.FREEBSD_VERSION }} \
          ${{ env.REGISTRY_PATH }}freebsd-amd64:${{ env.FREEBSD_VERSION }} \
          ${{ env.REGISTRY_PATH }}freebsd-arm64:${{ env.FREEBSD_VERSION }}

  push:
    name: Publish FreeBSD-${{ github.event.inputs.FREEBSD_VERSION || github.event.client_payload.freebsd_version }}
    needs: build_manifest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Store parameters in environmental variables
        run: |
          echo "FREEBSD_VERSION=${{ github.event.inputs.FREEBSD_VERSION || github.event.client_payload.freebsd_version }}" >> $GITHUB_ENV
          # XXX missing ${{ env.LATEST == true && 'latest' || '' }}
          # echo "LATEST=${{ github.event.inputs.LATEST || github.event.client_payload.latest }}" >> $GITHUB_ENV
          echo "REGISTRY_PATH=ghcr.io/${{ github.repository_owner }}/" >> $GITHUB_ENV

      - name: Push images to ghcr.io
        run: sudo buildah manifest push ${{ env.REGISTRY_PATH }}freebsd:${{ env.FREEBSD_VERSION }}
