name: Build FreeBSD Container Image

on:
  repository_dispatch:
    types:
      - build

  workflow_dispatch:
    inputs:
      ARCH:
        description: "Which architecture (amd64 or arm64) do you want to build? (Default: amd64)"
        type: choice
        options:
        - amd64
        - arm64
        default: amd64
        required: true
      LATEST:
        description: "Whether the 'latest' tag should be created (Default: false)"
        type: boolean
        default: false
        required: true

jobs:
  build:
    name: FreeBSD-${{ matrix.freebsd_version }}-${{ github.event.inputs.ARCH || github.event.client_payload.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        freebsd_version:
          - "15.0"
          - "14.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Store parameters in environmental variables
        run: |
          echo "FREEBSD_VERSION=${{ matrix.freebsd_version }}" >> $GITHUB_ENV
          echo "ARCH=${{ github.event.inputs.ARCH || github.event.client_payload.arch }}" >> $GITHUB_ENV
          echo "LATEST=${{ github.event.inputs.LATEST || github.event.client_payload.latest }}" >> $GITHUB_ENV

      - name: Show parameters
        run: |
          echo $FREEBSD_VERSION
          echo $ARCH
          echo $LATEST

      # XXX Use BSD tar
      - name: Build image
        run: |
          sudo sh ./build.sh --arch=${{ env.ARCH }} --freebsd_version=${{ env.FREEBSD_VERSION }} --latest_tag=${{ env.LATEST }}

      - name: Check image
        run: |
          podman images

          # XXX Settle on versioning
          if [[ "${{ env.FREEBSD_VERSION }}" != "15.0" ]]; then
            FREEBSD_VERSION_WITH_SUFFIX=${{ env.FREEBSD_VERSION }} # XXX -RELEASE
          else
            FREEBSD_VERSION_WITH_SUFFIX=${{ env.FREEBSD_VERSION }} # XXX -CURRENT
          fi
          if [[ "${{ env.ARCH }}" != "amd64" ]]; then
            ARCH_SUFFIX=-${{ env.ARCH }}
          fi
          podman run ghcr.io/${{ github.repository_owner }}/freebsd:${FREEBSD_VERSION_WITH_SUFFIX}${ARCH_SUFFIX} uname -a

      # - name: Login to ghcr.io
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GITHUB_PAT }}
      #     password: ${{ secrets.GITHUB_PAT }}

      # - name: Push images to ghcr.io
      #   run: podman push ghcr.io/${{ github.repository_owner }}/freebsd --all-tags
